linked_list : Main.c insert_node.c delete_node.c print_list.c
	gcc -o linked_list Main.c insert_node.c delete_node.c print_list.c reverse_list.c reverse_print_rec.c -I.

.PHONY: clean
clean:
	rm linked_list.exe
